source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'jquery-rails', '4.1.0'
gem 'mongo', '2.2.2'
gem 'mongoid', '~> 5.1.0'
gem 'bson_ext', '1.5.1'
gem 'simple_form', '3.2.1'
gem 'mongoid-paranoia', '1.3.0'
gem 'json', '1.8.3'
gem 'thin', '1.6.4'
gem 'net-ssh', '~>2.9.2'
gem 'mongoid-ancestry', '0.4.2'

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
end

group :assets do
  gem 'sass-rails',   '~> 5.0'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'twitter-bootstrap-rails', '~> 2.2.8'
  gem 'modernizr-rails', '2.7.1'
end
